## This is an example application.yml to be used in your main properties file
## Rename or delete this why you are using it
#
## Server
#server:
#  port: 8080 # Set your application port here
#
## Spring application
#spring:
#  application:
#    name: "microservice-template"
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    username: "root"
#    password: "root"
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: "jdbc:mysql://localhost:3306/alinedb"
#    initialization-mode: always
#
## App configurations
#app:
#  admin-portal: "http://localhost:3000"
#  member-dashboard: "http://localhost:4200"
#  landing-portal: "http://localhost:3007"
#  security:
#    secret-key: "ThisIsAGreatSecretKey!!!" # Change this in production to match the other microservices
#    jwt:
#      secret-key: "ThisIsAJWTAuthenticationSecretKey" # Change this in production to match the other microservices
#    disable-web-security: true # Remove or set this property to true to enable web security


